name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      FBT_NO_SYNC: 1
      FBT_GIT_SUBMODULE_SHALLOW: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Cache toolchain
        uses: actions/cache@v4
        with:
          path: toolchain
          key: ${{ runner.os }}-toolchain-v39-${{ runner.arch }}

      - name: Build firmware
        run: ./fbt COMPACT=1 DEBUG=0 updater_package

      - name: Build FAPs
        run: ./fbt COMPACT=1 DEBUG=0 fap_dist

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/f7-C/*.dfu
            dist/f7-C/*.bin
            dist/f7-C/*.tgz
            dist/f7-C/*.zip
